### PR TITLE
Slight refactoring of server code

### PR DESCRIPTION
**Pull request by embray**
I want to make a fix to the patchbot server (see #109) so I started playing with the server code for the first time.  The motivation of these patches was to make it easier to run a development server--this is currently broken because, although the `patchbot.serve` module had a `main` function in it and a `if __name__ == '__main__'` section, it doesn't work due to the use of relative imports.  You can't run a sub-module of a package as the `__main__` module if it has relative imports.

I thought it might make sense to make the patchbot *server* a separate sub-package anyways, so this moves all the server-specific code and resources to `sage_patchbot.server`, which also now has a `__main__.py` module.  This means you can now run `python -m sage_patchbot.server` to run a development server.

### CODE REVIEW

**Comment by fchapoton** [comment]
Did you take care of eventual needed changes in the serve.wsgi file ?
Using this branch would currently break our main patchbot server. Maybe caused by the move of this file.

**Comment by embray** [comment]
I'll have to take a look at that documentation (where, exactly?) for how the main server is deployed.  Normally it doesn't make a lot of sense to have trivial `.wsgi` files living in the Python package itself, especially one with site-specific paths like the:

```
sys.path.append('/home/patchbot/sage-patchbot')
```

Though I wonder (I'll have to try) if something like this would work:  If the `serve.wsgi` file lives at the root of the `sage_patchbot` package (as it did before I moved it) one could change it to something like:

```
from os.path import join, abspath, dirname
sys.path.insert(0, abspath(join('..', dirname(__file__)))
```

Then you configure the webserver (as it presumably already is) to `/path/to/sage_patchbot/serve.wsgi`, and the `.wsgi` module itself ensures that its package's directory is inserted on `sys.path`.  I don't know if `__file__` is set on WSGI modules, but it should be...

**Comment by embray** [comment]
In other words, I could move the `serve.wsgi`, at least, back to its original location if it's easier. But I think it would be good to remove hard-coded paths from it if possible.

**Comment by fchapoton** [comment]
The documentation for the patchbot server is available only inside the patchbot server (and is not very detailed). You need to have an account, do you want one ?

**Comment by embray** [comment]
Sure--I can't see any of the admin backend.

But just to confirm, would moving the .wsgi module back to its original location improve matters?

**Comment by embray** [comment]
@fchapoton Did you ever make me an account for the patchbot server?  I would like to finish this up so I can also deploy the fix from #111.

**Comment by fchapoton** [comment]
Send me your public ssh key and the IP range by which you want to access
the machine.

2017-08-24 13:00 GMT+02:00 Erik Bray <notifications@github.com>:

**Comment by fchapoton** [comment]
Did you receive my mail (send to your lri address ?)

2017-08-24 13:23 GMT+02:00 Frédéric Chapoton <fchapoton2@gmail.com>:

**Comment by embray** [comment]
Ah, the one I always forget to check.  I'll look now.

**Comment by embray** [comment]
Now I understand that the patchbot is being updated just by updating a local clone of the git repository.  I guess that's convenient, if nothing else.

**Comment by embray** [comment]
Rebased on current master.  I moved serve.wsgi back to the top level of the package, but updated it to work independently of where the package is installed (as suggested in https://github.com/sagemath/sage-patchbot/pull/110#issuecomment-313048176).  It should work now, after merging this, to just do an a git pull to update the live patchbot (and a restart of uwsgi).

**Comment by fchapoton** [comment]
So let us try right now, ok ?

**Comment by fchapoton** [comment]
This does not work (browser shows "Internal server error")

**Comment by embray** [comment]
It's working for me?  Or did you revert?

**Comment by embray** [comment]
I see--I just left a typo in the `serve.wsgi`.  There was a missing paren.

**Comment by fchapoton** [comment]
Did you look at the file Admin/Documentation ? We may need to modify the uwsgi configuration ?

**Comment by embray** [comment]
No, I deliberately left things so the uwsgi config itself should not need updating.  Looking at the logs it failed at importing, so I guess it doesn't like my position-independent .wsgi file after all.  It's working for me, but I'm not using uWSGI to run it so maybe that has something to do.

**Comment by fchapoton** [comment]
I let you try to handle this, ok ?

**Comment by embray** [comment]
Yep, I'm on it.  Thanks!

**Comment by embray** [comment]
Whew, it works now.  I just had numerous stupid bugs in the .wsgi script.

**Comment by fchapoton** [comment]
Then the simplest thing is probably to make a new pull request, no ?

**Comment by embray** [comment]
I just made commits direct to master.

**Comment by fchapoton** [comment]
ok, perfect

**Pull request merged**
