### PR TITLE
remove trusted users

### LINKED ISSUE #121: Get rid of "trusted authors" feature
The trusted authors check is presumably intended as a security feature; but, as discussed on sage-devel at (https://groups.google.com/forum/#!topic/sage-devel/rSaesTu4MCE), it provides no actual security, because anyone with a trac account can set ticket "Author" fields to whatever they like. It also has the pernicious effect of making it harder for new Sage contributors to get their code positively reviewed. So I propose that this feature be removed, or at least disabled by default.

### PR DESCRIPTION
**Pull request by videlec**
We do remove the concept of "trusted users" from client and server (fixes #121)

### CODE REVIEW

**Comment by fchapoton** [comment]
I disagree, but will not oppose.

**Comment by embray** [comment]
I'm +1 on this but it might have been nice to have some announcement that this was changed (since it required an update to the patchbot client--otherwise it dies trying to find the trusted authors list now).

**Comment by videlec** [comment]
How would you announce it? We can have an empty list of trusted users on the server that would also prevent the patchbot from doing anything. But I don't see the difference. Of course, something needs to be done on the wiki https://wiki.sagemath.org/buildbot before the release.

**Comment by embray** [comment]
@videlec I just meant a note, sage, on sage-devel that patchbot clients would need to be upgraded.  Because now when they try to contact the server for the trusted authors list it sits there for a while getting 404s and then gives up, and then no tests work.

That's fine--I'm just saying that if a change to the server can't be made in a way that's backwards-compatible for old clients then this should be pointed out rather than patchbots starting to break unexpectedly.

**Comment by fchapoton** [comment]
my fault. I should not have upgraded the server without saying it loud on sage-devel. Now we need to make a patchbot "release" 2.7.1 and ask all clients to update.

**Comment by fchapoton** [comment]
or re-introduce the code on the server side, that was deleted with no reason..

**Pull request merged**
